name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]   # déploie à chaque push sur main
  workflow_dispatch:      # permet de lancer manuellement

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Prépare l’artefact pour Pages (dossier "_site")
      - name: Prepare Pages artifact
        run: |
          rm -rf _site
          cp -r dist _site
          # SPA fallback (évite les pages blanches sur routes React)
          cp _site/index.html _site/404.html || true
          # Domaine personnalisé
          echo infonex.fr > _site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy-step.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deploy-step
        uses: actions/deploy-pages@v4
